### ISSUE TITLE
Add a explanation to use Signal Desktop on Windows

### ISSUE THREAD

**Issue by Kcchouette** [shvchk/Signal-Desktop-installer#2]
Here what I've done:
1. Download the latest (normal) version of NW.js: https://nwjs.io/
2. Download the Signal Desktop package: https://github.com/shvchk/Signal-Desktop-installer/blob/master/install.py#L7
3. Extract it using for example 7-zip
4. Using Windows PowerShell, go to the Signal folder (where the extract of the (3) is) (for example `cd C:\Users\XXXX\Downloads\Signal`
5. Launch `C:\<the_path_where_nw_is_extract>\nw.exe .` in this folder

**Comment by shvchk** [comment]
There is now [official Windows version](https://signal.org/download/).
